#!/usr/bin/env bash
# Records (or re-records) the tp1 golden token streams for one ninfer binary.
#
# Usage: tests/data/tp1-golden/record.sh <ninfer-binary> <artifact> <output-dir>
#   TP1_GPU  physical GPU index to run on (default 0)
#
# The three cases cover three prefill regimes on the same greedy, no-thinking,
# 128-new-token decode: a short chat turn (23 prompt tokens), a ~2k-token
# instruction (2,191), and a ~30k-token document (28,677, int8 KV so it fits
# beside the weights). Prompts are generated by make_prompts.py, not checked in.
#
# For each case it writes three files into the output directory:
#   case-N.ids       the CLI's `tokens generated ids` row, ids only
#   case-N.txt       the generated content exactly as it reached stdout
#   case-N.summary   the load/run summary rows that are deterministic for a
#                    fixed binary+artifact+workload and are printed by BOTH
#                    upstream feaf4dd and this fork
#
# The summary filter drops elapsed/speed/throughput rows (wall-clock), the
# three free-memory rows (they depend on whatever else is resident on the GPU),
# and `CUDA Graph memory` -- that row is the driver's own accounting of the
# instantiated graphs and it varies run to run for a FIXED binary (2.12 / 2.00 /
# 2.00 MiB over three consecutive identical runs of this fork's CLI), so it
# cannot distinguish anything. It also drops the rows this fork added that
# upstream does not print (`tensor parallel`, `rope`, `gpu0 *`), so one recorded
# file compares across both.
set -euo pipefail

if [[ $# -ne 3 ]]; then
    echo "usage: $0 <ninfer-binary> <artifact> <output-dir>" >&2
    exit 2
fi

BIN="$1"
ART="$2"
OUTDIR="$3"
GPU="${TP1_GPU:-0}"
HERE="$(cd "$(dirname "$0")" && pwd)"

[[ -x "$BIN" ]] || { echo "not executable: $BIN" >&2; exit 1; }
[[ -f "$ART" ]] || { echo "artifact not found: $ART" >&2; exit 1; }

mkdir -p "$OUTDIR"
PROMPTS="$OUTDIR/prompts"
python3 "$HERE/make_prompts.py" "$PROMPTS"

# case index : messages file : extra flags
CASES=(
    "1:case-1-short.json:--max-context 4096"
    "2:case-2-instruction.json:--max-context 4096"
    "3:case-3-document.json:--max-context 32768 --kv-dtype int8"
)

for entry in "${CASES[@]}"; do
    idx="${entry%%:*}"
    rest="${entry#*:}"
    msgs="${rest%%:*}"
    flags="${rest#*:}"
    err="$OUTDIR/case-$idx.stderr"
    # shellcheck disable=SC2086 -- $flags is a deliberate word-split flag list.
    CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES="$GPU" \
        "$BIN" "$ART" \
        --messages "$PROMPTS/$msgs" \
        $flags --max-new 128 --greedy --no-thinking --print-token-ids \
        >"$OUTDIR/case-$idx.txt" 2>"$err"

    grep -E '^tokens +generated ids ' "$err" |
        sed -E 's/^tokens +generated ids +//' >"$OUTDIR/case-$idx.ids"
    [[ -s "$OUTDIR/case-$idx.ids" ]] || {
        echo "case $idx produced no token ids (is --print-token-ids supported?)" >&2
        exit 1
    }

    grep -E '^summary ' "$err" |
        grep -vE '^summary +(model elapsed|prefill speed|decode speed|throughput \(overall\)|free after weights|free after startup|planned slack|CUDA Graph memory|tensor parallel|rope|gpu0 )' |
        sed -E 's/[[:space:]]+/ /g' >"$OUTDIR/case-$idx.summary"
    rm -f "$err"
done

rm -rf "$PROMPTS"
echo "recorded 3 cases into $OUTDIR"
